services:
  postgres:
    image: 'postgres:latest'
    container_name: 'tinkoffdb'
    environment:
      - 'POSTGRES_DB=db'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5435:5432'
