package com.itmo.tinkoffinvestementbot.model.enums.bot;

public enum BotState {
    BOT_VERSION_COMMAND, HELP_COMMAND,

    START, FIRST_START,

    TRADING_MENU, NOTIFICATION_MENU, ACCOUNT_SETTINGS, HELP, BACK,

    START_TRADING, TRADINGS_LIST, STRATEGIES_LIST,


    CREATE_NOTIFICATION_EVENT, NOTIFICATION_EVENT_LIST,

    INVEST_ACCOUNT_ACTION, ENTER_TOKEN
}
